### ISSUE TITLE
Error using autofitVariogramST

### ISSUE THREAD

**Issue by miguelgcu** [sigmafelix/autoSTK#1]
Hello. 
I wanna report an error with:
I used temperature information for my STFDF object.
Thanks for ur help.

v_stk<- autofitVariogramST(datos_STFDF,values ~ 1)

  |============================================================| 100%
          np    dist     gamma   id timelag spacelag avgDist
2    5108886 0.33196 0.3189710 lag0  0 days      250 0.33196
42    283790 0.00000 0.4311195 lag1  1 days        0 0.00000
43  10216440 0.33196 0.4297990 lag1  1 days      250 0.33196
83    283753 0.00000 0.5638979 lag2  2 days        0 0.00000
84  10215108 0.33196 0.5561521 lag2  2 days      250 0.33196
124   283716 0.00000 0.6718891 lag3  3 days        0 0.00000
125 10213776 0.33196 0.6670738 lag3  3 days      250 0.33196
165   283679 0.00000 0.7382632 lag4  4 days        0 0.00000
166 10212444 0.33196 0.7378229 lag4  4 days      250 0.33196
206   283642 0.00000 0.7915491 lag5  5 days        0 0.00000
207 10211112 0.33196 0.7914823 lag5  5 days      250 0.33196
247   283605 0.00000 0.8531401 lag6  6 days        0 0.00000
248 10209780 0.33196 0.8485189 lag6  6 days      250 0.33196
          np    dist     gamma   id timelag spacelag avgDist
2    5108886 0.33196 0.3189710 lag0  0 days      250 0.33196
42    283790 0.00000 0.4311195 lag1  1 days        0 0.00000
43  10216440 0.33196 0.4297990 lag1  1 days      250 0.33196
83    283753 0.00000 0.5638979 lag2  2 days        0 0.00000
84  10215108 0.33196 0.5561521 lag2  2 days      250 0.33196
124   283716 0.00000 0.6718891 lag3  3 days        0 0.00000
125 10213776 0.33196 0.6670738 lag3  3 days      250 0.33196
165   283679 0.00000 0.7382632 lag4  4 days        0 0.00000
166 10212444 0.33196 0.7378229 lag4  4 days      250 0.33196
206   283642 0.00000 0.7915491 lag5  5 days        0 0.00000
207 10211112 0.33196 0.7914823 lag5  5 days      250 0.33196
247   283605 0.00000 0.8531401 lag6  6 days        0 0.00000
248 10209780 0.33196 0.8485189 lag6  6 days      250 0.33196

Error in `$<-.data.frame`(`*tmp*`, "dir.hor", value = 0) : 
  replacement has 1 row, data has 0

**Comment by sigmafelix** [comment]
Hi @Doltrix,
Thank you for reporting the issue. I am working on it and hopefully push updates soon.

**Comment by sigmafelix** [comment]
* Share your `reprex` here would help a lot!
I think that you kept your `cutoff` and `width` values as default, which may lead to errors depending on the spatial scale of your data. Could you change `cutoff` and `width` values for your input data and share `reprex` with me?

Thank you.

**Comment by sigmafelix** [comment]
I hope that your issue was resolved. I will close this issue. Please reopen the issue if you still find the same error after setting proper `cutoff` and `width` values.
